services:
  db:
    image: postgres:15-alpine
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 1s
      retries: 10

  migrate:
    image: ghcr.io/kukymbr/goose-docker:3.24.3
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations
    env_file:
      - .env
    environment:
      GOOSE_DRIVER: postgres
      GOOSE_DBSTRING: postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}?sslmode=${DB_SSLMODE}
    command: ["up"]

  app:
    build: .
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${GRPC_PORT}:${GRPC_PORT}"
