services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: trade-charts
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    ports: ["5432:5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testuser -d testdb"]
      interval: 1s
      retries: 10

  migrate:
    image: ghcr.io/kukymbr/goose-docker:3.24.3
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations
    environment:
      - GOOSE_DRIVER=postgres
      - GOOSE_DBSTRING=host=db port=5432 user=testuser password=testpass dbname=trade-charts sslmode=disable
    command: ["up"]
